kind: pipeline
name: default

.node-image: &node-image
  image: node:10-alpine

steps:

- name: check dependencies
  <<: *node-image
  commands:
    - npm audit

- name: install dependencies
  <<: *node-image
  commands:
    - npm ci

- name: lint javascript
  <<: *node-image
  commands:
    - npm run linter:js

- name: unit tests
  <<: *node-image
  commands:
    - npm run test:unit

- name: dev release
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKERHUB_USERNAME
    password: 
      from_secret: DOCKERHUB_PASSWORD
    repo: alsmith/lighthouse-failures
    tags:
      - dev
  when:
    branch:
      exclude:
        - master
    event:
      - push

- name: master release
  image: plugins/docker
  settings:
    username: 
      from_secret: DOCKERHUB_USERNAME
    password: 
      from_secret: DOCKERHUB_PASSWORD
    repo: alsmith/lighthouse-failures
    tags:
      - edge
  when:
    branch:
      include:
        - master
    event:
      - push

- name: tag release
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKERHUB_PASSWORD
    repo: alsmith/lighthouse-failures
  when:
    event:
      - tag
    